---
# Source: my-demoapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app-my-demoapp
spec:
  type: ClusterIP
  selector:
    app: my-demoapp
  ports:
    - port: 8080
      targetPort: 8080
---
# Source: my-demoapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-my-demoapp
  labels:
    helm.sh/chart: my-demoapp-0.1.0
    app.kubernetes.io/name: my-demoapp
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-demoapp
  template:
    metadata:
      labels:
        app: my-demoapp
    spec:
      serviceAccountName: my-app-my-demoapp
      containers:
        - name: my-demoapp
          image: ":"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
---
# Source: my-demoapp/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-my-demoapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-my-demoapp
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# Source: my-demoapp/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-my-demoapp
spec:
  ingressClassName: nginx
  rules:
    - host: my-demoapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-my-demoapp
                port:
                  number: 8080
---
# Source: my-demoapp/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "my-app-my-demoapp-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ['curl']
      args: ['http://my-app-my-demoapp:8080']
  restartPolicy: Never
