apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "my-demoapp.fullname" . }}-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ['curl']
      args: ['http://{{ include "my-demoapp.fullname" . }}:{{ .Values.service.port }}']
  restartPolicy: Never
















